version: "2"
services:

  app:
    build: ./app
    image : app
    volumes:
      - ./app/functions:/var/www/functions
      - ./app/src:/var/www/src
      - ./app/run.py:/var/www/run.py
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
